name: cicd-release

on:  
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      release:
        required: true
        type: string

jobs:
  release:
    name: post-jar-to-release-page
    runs-on: ubuntu-latest
    environment:  ${{ inputs.environment }}
    permissions:
      contents: write
    steps:
      
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls 
          ls target
          ls staging
#          gh release create ${{ inputs.release }} ./target/cicd-testing-v1-${{ inputs.release }}-mule-application.jar --title "${{ inputs.release }}" --generate-notes

