name: cicd-release

on:  
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      release:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    environment:  ${{ inputs.environment }}
    steps:
      
      - name: Create release
        env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        GITHUB_REF_NAME: ${{ github.ref_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "The version extracted from XML is ${{ env.version }}"
          gh release create ${{ inputs.release }} ./target/cicd-testing-v1-${{ inputs.release }}-mule-application.jar --title "${{ inputs.release }}" --generate-notes
          
      # - name: init-release
      #   if: ${{ vars.ENV == 'DEV' }}
      #   run: echo 'Release ${{ needs.deployment.outputs.version_number }} to ${{ vars.ENV }} is successful!'
